apiVersion: v1
kind: Service
metadata:
  name: amber-agent
  labels:
    app: chatbot
    component: amber-agent
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: chatbot
    component: amber-agent
