apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  labels:
    app: chatbot
    component: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
