apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  labels:
    app: chatbot
    component: postgresql
type: Opaque
data:
  POSTGRESQL_USER: YW1iZXI=
  POSTGRESQL_PASSWORD: UkVQTEFDRV9NRQ==
  POSTGRESQL_DATABASE: YW1iZXI=
