apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  labels:
    app: chatbot
    component: postgresql
type: Opaque
data:
  POSTGRESQL_USER: YW1iZXI=
  POSTGRESQL_PASSWORD: RUxHS0w1dFVRUTh1c2hRT296dWdtdmo=
  POSTGRESQL_DATABASE: YW1iZXI=
