apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: template-ui
  labels:
    app: chatbot
    component: ui
spec:
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 1
  output:
    to:
      kind: ImageStreamTag
      name: template-ui:latest
  source:
    type: Git
    git:
      uri: https://github.com/jeremyeder/template-ui
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  triggers: []
