apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: template-ui
  labels:
    app: chatbot
    component: ui
spec:
  to:
    kind: Service
    name: template-ui
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
